name: Your New Jekyll Site
markdown: redcarpet
pygments: true

# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
#permalink: /:categories/:year/:month/:day/:title 
permalink: /:title 

# Comments System
# This is the key for the Disqus comments system. Get one from http://disqus.com/
disqus_shortname: jekyllfoundationdemo

# Contact Form
# The api key for getsimpleform. Get one from http://getsimpleform.com
contactform_enabled: true 
contactform_apitoken: f70a375b83a60ecfafe284aec39cd227


# Google Analytics
analytics_enabled: true
analytics_key: UA-13112699-12
analytics_site: jekyllfoundationquickstart.herokuapp.com

# Heroku Deployment
# Exclude files that are used for deployment (in this case deploying to Heroku)
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]