name: Your New Jekyll Site
markdown: redcarpet
pygments: true

# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
#permalink: /:categories/:year/:month/:day/:title 
permalink: /:title 

# This is the key for the Disqus comments system 
disqus_shortname: jekyllfoundationdemo

# Exclude files that are used for deployment (in this case deploying to Heroku)
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor]"